import type { Metadata } from "next";
import Header from "@/lib/components/_header/Header";
import Sidebar from "@/lib/components/_sidebar/Sidebar";
import { AuthProvider } from "@/lib/context/AuthContext";
import styles from '../../lib/styles/dashboard.module.scss';
import Router from "@/lib/components/_dashboard/components/Router";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.root}>
      <AuthProvider>
        <Router>
          <>
            <Header />
            <main className={styles.root__main}>
              <Sidebar />
              <div className={styles.root__children}>
                {children}
              </div>
            </main>
            </>
        </Router>
      </AuthProvider>
    </div>
  );
}
